### ISSUE TITLE
Dconf2nix hangs (see #52 and #53)

### ISSUE THREAD

**Issue by Krutonium** [gvolpe/dconf2nix#51] opened 2021-12-11 00:20 UTC
Alright so I made a dump of my dconf as described in readme, then I fed it to the tool, it timed out so I gave it a longer timeout .

Then my system got super laggy so I opened htop to find it using most of my systems 32 GB of memory. Will attach dconf file once my computer is usable again.![IMG_20211210_191611.jpg](https://user-images.githubusercontent.com/3945538/145656392-13914b0a-39ec-4617-aeaf-ec693a1dfb8f.jpg)

**Comment by Krutonium** [comment] 2021-12-11 00:21
[dconf.settings.txt](https://github.com/gvolpe/dconf2nix/files/7696081/dconf.settings.txt)

**Comment by gvolpe** [comment] 2021-12-11 14:28
Please, indicate the `dconf2nix` version. 

It does not hang on `0.0.8` or newer versions, but it fails with some other errors. The first one is because of this entry:

```
[gnome.desktop.interface]
cursor-theme='Yaru'
```

It uses `.` instead of `/`, which is not supported by `dconf2nix` (and it won't be for now), see https://github.com/gvolpe/dconf2nix/issues/47

The other two errors happen because of #52 and #53, which I just reproduced and raised.

**Comment by gvolpe** [comment] 2021-12-11 14:30
FWIW 90 seconds of timeout is too much. The default is 5 seconds, which should be enough.

**Comment by Krutonium** [comment] 2021-12-11 20:56
I know, but I was curious if more time would let it finish. TL;DR it did not.

**Comment by gvolpe** [comment] 2021-12-13 09:27
@Krutonium can you indicate which version? It finishes for me with a timeout in `0.0.8` and `0.0.10`.

Also, can you tell what application generates this entry? Seems like a gtk theme or so.

```
[gnome.desktop.interface]
cursor-theme='Yaru'
```

I'm considering adding support for #47, as now there are two reported cases.

**Comment by gvolpe** [comment] 2021-12-13 16:32
Closing this as the original issues #52 and #53 have been fixed.

**Closed by gvolpe** 2021-12-13 16:32 UTC

**Comment by Krutonium** [comment] 2021-12-14 03:25
Yeah it times out for me too, eventually lol. 

As for the entry with the periods, that's how the value gets inserted if you do it via bash and use the wrong separator, at least for me. That said, it does seem to work just fine?
